import type { Metadata } from "next";
import { Racing_Sans_One } from 'next/font/google';
import "./globals.css";
import NavBar from "@/components/nav-bar/nav-bar";

const racingSansOne = Racing_Sans_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-racing',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${racingSansOne.variable}`}
      >
        <header>
          <NavBar />
        </header>
        {children}
      </body>
    </html>
  );
}
